[package]
name = "quotes"
version = "0.1.0"
edition = "2018"
default-run = "quotes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
refinery = { version = "0.6", features = ["rusqlite"] }
rocket = "0.5.0-rc.1"
rusqlite = "0.25.3"
#tokio = { version = "0.2", features = ["macros"] }
#serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"
gumdrop = "0.8.0"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["sqlite_pool"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]
